//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarTenderEtiketak.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cms.sammic.com:8080/", ConfigurationName="ServiceReference1.EtiquetadoApiPortType")]
    public interface EtiquetadoApiPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.sammic.com:8080/api_getSpecsEtiquetado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        BarTenderEtiketak.ServiceReference1.EtiquetadoBean api_getSpecsEtiquetado(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.sammic.com:8080/api_getSpecsEtiquetado", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<BarTenderEtiketak.ServiceReference1.EtiquetadoBean> api_getSpecsEtiquetadoAsync(string codigo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cms.sammic.com:8080/")]
    public partial class EtiquetadoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string revisionField;
        
        private string aprobadoImDField;
        
        private string aprobadoComField;
        
        private string nombre_esField;
        
        private string nombre_enField;
        
        private string claveModeloField;
        
        private string potenciaField;
        
        private string frecuenciaField;
        
        private string tension1Field;
        
        private string tension2Field;
        
        private string tension3Field;
        
        private string tensionDCField;
        
        private string fase1Field;
        
        private string fase2Field;
        
        private string fase3Field;
        
        private string intensidad1Field;
        
        private string intensidad2Field;
        
        private string intensidad3Field;
        
        private string intensidadDCField;
        
        private string potMaximaField;
        
        private string potMotorField;
        
        private string potCalderinField;
        
        private string potCubaField;
        
        private string presionBarField;
        
        private string pVacField;
        
        private string ipField;
        
        private string caudalBombaField;
        
        private string clAislamientoField;
        
        private string condensadorField;
        
        private string especificaciones1Field;
        
        private string etiketaMotaField;
        
        private string etiketaFormatoField;
        
        private string etiketakField;
        
        private string etiketaOrriakField;
        
        private string etiketaGarantiaField;
        
        private string bezeroRef1Field;
        
        private string bezeroRef2Field;
        
        private string directivasField;
        
        private string normas1Field;
        
        private string normas2Field;
        
        private string normas3Field;
        
        private string notasPlacaField;
        
        private string formatoLaserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("revision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string aprobadoImD {
            get {
                return this.aprobadoImDField;
            }
            set {
                this.aprobadoImDField = value;
                this.RaisePropertyChanged("aprobadoImD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string aprobadoCom {
            get {
                return this.aprobadoComField;
            }
            set {
                this.aprobadoComField = value;
                this.RaisePropertyChanged("aprobadoCom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre_es {
            get {
                return this.nombre_esField;
            }
            set {
                this.nombre_esField = value;
                this.RaisePropertyChanged("nombre_es");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre_en {
            get {
                return this.nombre_enField;
            }
            set {
                this.nombre_enField = value;
                this.RaisePropertyChanged("nombre_en");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string claveModelo {
            get {
                return this.claveModeloField;
            }
            set {
                this.claveModeloField = value;
                this.RaisePropertyChanged("claveModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string potencia {
            get {
                return this.potenciaField;
            }
            set {
                this.potenciaField = value;
                this.RaisePropertyChanged("potencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string frecuencia {
            get {
                return this.frecuenciaField;
            }
            set {
                this.frecuenciaField = value;
                this.RaisePropertyChanged("frecuencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string tension1 {
            get {
                return this.tension1Field;
            }
            set {
                this.tension1Field = value;
                this.RaisePropertyChanged("tension1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string tension2 {
            get {
                return this.tension2Field;
            }
            set {
                this.tension2Field = value;
                this.RaisePropertyChanged("tension2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tension3 {
            get {
                return this.tension3Field;
            }
            set {
                this.tension3Field = value;
                this.RaisePropertyChanged("tension3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string tensionDC {
            get {
                return this.tensionDCField;
            }
            set {
                this.tensionDCField = value;
                this.RaisePropertyChanged("tensionDC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string fase1 {
            get {
                return this.fase1Field;
            }
            set {
                this.fase1Field = value;
                this.RaisePropertyChanged("fase1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string fase2 {
            get {
                return this.fase2Field;
            }
            set {
                this.fase2Field = value;
                this.RaisePropertyChanged("fase2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string fase3 {
            get {
                return this.fase3Field;
            }
            set {
                this.fase3Field = value;
                this.RaisePropertyChanged("fase3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string intensidad1 {
            get {
                return this.intensidad1Field;
            }
            set {
                this.intensidad1Field = value;
                this.RaisePropertyChanged("intensidad1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string intensidad2 {
            get {
                return this.intensidad2Field;
            }
            set {
                this.intensidad2Field = value;
                this.RaisePropertyChanged("intensidad2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string intensidad3 {
            get {
                return this.intensidad3Field;
            }
            set {
                this.intensidad3Field = value;
                this.RaisePropertyChanged("intensidad3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string intensidadDC {
            get {
                return this.intensidadDCField;
            }
            set {
                this.intensidadDCField = value;
                this.RaisePropertyChanged("intensidadDC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string potMaxima {
            get {
                return this.potMaximaField;
            }
            set {
                this.potMaximaField = value;
                this.RaisePropertyChanged("potMaxima");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string potMotor {
            get {
                return this.potMotorField;
            }
            set {
                this.potMotorField = value;
                this.RaisePropertyChanged("potMotor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string potCalderin {
            get {
                return this.potCalderinField;
            }
            set {
                this.potCalderinField = value;
                this.RaisePropertyChanged("potCalderin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string potCuba {
            get {
                return this.potCubaField;
            }
            set {
                this.potCubaField = value;
                this.RaisePropertyChanged("potCuba");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string presionBar {
            get {
                return this.presionBarField;
            }
            set {
                this.presionBarField = value;
                this.RaisePropertyChanged("presionBar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string pVac {
            get {
                return this.pVacField;
            }
            set {
                this.pVacField = value;
                this.RaisePropertyChanged("pVac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string iP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("iP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string caudalBomba {
            get {
                return this.caudalBombaField;
            }
            set {
                this.caudalBombaField = value;
                this.RaisePropertyChanged("caudalBomba");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string clAislamiento {
            get {
                return this.clAislamientoField;
            }
            set {
                this.clAislamientoField = value;
                this.RaisePropertyChanged("clAislamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string condensador {
            get {
                return this.condensadorField;
            }
            set {
                this.condensadorField = value;
                this.RaisePropertyChanged("condensador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string especificaciones1 {
            get {
                return this.especificaciones1Field;
            }
            set {
                this.especificaciones1Field = value;
                this.RaisePropertyChanged("especificaciones1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string etiketaMota {
            get {
                return this.etiketaMotaField;
            }
            set {
                this.etiketaMotaField = value;
                this.RaisePropertyChanged("etiketaMota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string etiketaFormato {
            get {
                return this.etiketaFormatoField;
            }
            set {
                this.etiketaFormatoField = value;
                this.RaisePropertyChanged("etiketaFormato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string etiketak {
            get {
                return this.etiketakField;
            }
            set {
                this.etiketakField = value;
                this.RaisePropertyChanged("etiketak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string etiketaOrriak {
            get {
                return this.etiketaOrriakField;
            }
            set {
                this.etiketaOrriakField = value;
                this.RaisePropertyChanged("etiketaOrriak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string etiketaGarantia {
            get {
                return this.etiketaGarantiaField;
            }
            set {
                this.etiketaGarantiaField = value;
                this.RaisePropertyChanged("etiketaGarantia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string bezeroRef1 {
            get {
                return this.bezeroRef1Field;
            }
            set {
                this.bezeroRef1Field = value;
                this.RaisePropertyChanged("bezeroRef1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string bezeroRef2 {
            get {
                return this.bezeroRef2Field;
            }
            set {
                this.bezeroRef2Field = value;
                this.RaisePropertyChanged("bezeroRef2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string directivas {
            get {
                return this.directivasField;
            }
            set {
                this.directivasField = value;
                this.RaisePropertyChanged("directivas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string normas1 {
            get {
                return this.normas1Field;
            }
            set {
                this.normas1Field = value;
                this.RaisePropertyChanged("normas1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string normas2 {
            get {
                return this.normas2Field;
            }
            set {
                this.normas2Field = value;
                this.RaisePropertyChanged("normas2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string normas3 {
            get {
                return this.normas3Field;
            }
            set {
                this.normas3Field = value;
                this.RaisePropertyChanged("normas3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string notasPlaca {
            get {
                return this.notasPlacaField;
            }
            set {
                this.notasPlacaField = value;
                this.RaisePropertyChanged("notasPlaca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string formatoLaser {
            get {
                return this.formatoLaserField;
            }
            set {
                this.formatoLaserField = value;
                this.RaisePropertyChanged("formatoLaser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EtiquetadoApiPortTypeChannel : BarTenderEtiketak.ServiceReference1.EtiquetadoApiPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EtiquetadoApiPortTypeClient : System.ServiceModel.ClientBase<BarTenderEtiketak.ServiceReference1.EtiquetadoApiPortType>, BarTenderEtiketak.ServiceReference1.EtiquetadoApiPortType {
        
        public EtiquetadoApiPortTypeClient() {
        }
        
        public EtiquetadoApiPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EtiquetadoApiPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtiquetadoApiPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtiquetadoApiPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BarTenderEtiketak.ServiceReference1.EtiquetadoBean api_getSpecsEtiquetado(string codigo) {
            return base.Channel.api_getSpecsEtiquetado(codigo);
        }
        
        public System.Threading.Tasks.Task<BarTenderEtiketak.ServiceReference1.EtiquetadoBean> api_getSpecsEtiquetadoAsync(string codigo) {
            return base.Channel.api_getSpecsEtiquetadoAsync(codigo);
        }
    }
}
